spring:
  application:
    name: mc-credit-disbursement-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:customer_db}?sslmode=disable
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:adminpostgres1%}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8082}

feign:
  clients:
    account:
      name: account-service
      url: http://mc-account-service:8081/accounts